kc_dict = {
    'Arecanut': [],
    'Arhar/Tur': [],
    'Bajra': [],
    'Banana': [],
    'Barley': [],
    'Black pepper': [],
    'Cardamom': [],
    'Cardamom': [],
    'Castor seed': [],
    'Coconut': [],
    'Coriander': [],
    'Cotton(lint)': [],
    'Cowpea(Lobia)': [],
    'Dry chillies': [],
    'Garlic': [],
    'Ginger': [],
    'Gram': [],
    'Groundnut': [],
    'Guar seed': [],
    'Horse-gram': [],
    'Jowar': [],
    'Jute': [],
    'Khesari': [],
    'Linseed': [0.45, 0.75, 1.15, 0.75],
    'Flax': [0.45, 0.75, 1.15, 0.75],
    'Maize': [],
    'Maize': [],
    'Mesta': [],
    'Moong(Green Gram)': [],
    'Moth': [],
    'Niger seed': [],
    'Oilseeds total': [],
    'Onion': [],
    'Other Rabi pulses': [],
    'Other Cereals': [],
    'Other Kharif pulses': [],
    'other oilseeds': [],
    'Other Summer Pulses': [],
    'Peas & beans (Pulses)': [],
    'Potato': [],
    'Ragi': [],
    'Rapeseed &Mustard': [],
    'Rice': [],
    'Safflower': [],
    'Sannhamp': [],
    'Sesamum': [],
    'Small millets': [],
    'Soyabean': [],
    'Sugarcane': [],
    'Sunflower': [],
    'Sweet potato': [],
    'Tapioca': [],
    'Tobacco': [],
    'Turmeric': [],
    'Urad': [],
    'Wheat': []
}

crop_period = {
    'Arecanut': [],
    'Arhar/Tur': [],
    'Bajra': [],
    'Banana': [],
    'Barley': [],
    'Black pepper': [],
    'Cardamom': [],
    'Cardamom': [],
    'Castor seed': [],
    'Coconut': [],
    'Coriander': [],
    'Cotton(lint)': [],
    'Cowpea(Lobia)': [],
    'Dry chillies': [],
    'Garlic': [],
    'Ginger': [],
    'Gram': [],
    'Groundnut': [],
    'Guar seed': [],
    'Horse-gram': [],
    'Jowar': [],
    'Jute': [],
    'Khesari': [],
    'Linseed': [195, 30, 50, 65, 50],
    'Flax': [195, 30, 50, 65, 50],
    'Maize': [],
    'Maize': [],
    'Mesta': [],
    'Moong(Green Gram)': [],
    'Moth': [],
    'Niger seed': [],
    'Oilseeds total': [],
    'Onion': [],
    'Other Rabi pulses': [],
    'Other Cereals': [],
    'Other Kharif pulses': [],
    'other oilseeds': [],
    'Other Summer Pulses': [],
    'Peas & beans (Pulses)': [],
    'Potato': [],
    'Ragi': [],
    'Rapeseed &Mustard': [],
    'Rice': [],
    'Safflower': [],
    'Sannhamp': [],
    'Sesamum': [],
    'Small millets': [],
    'Soyabean': [],
    'Sugarcane': [],
    'Sunflower': [],
    'Sweet potato': [],
    'Tapioca': [],
    'Tobacco': [],
    'Turmeric': [],
    'Urad': [],
    'Wheat': []
}